services:
  metabase:
    image: metabase/metabase:latest
    container_name: osha-metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    volumes:
      - ./metabase-data:/metabase-data
